<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_kestats_backend"
 *
 * Auto generated by Extension Builder 2016-06-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ke_stats backend',
	'description' => 'This extension provides a working backend module for TYPO3 CMS 7 LTS. (CSV-Download does not work yet.)',
	'category' => 'module',
	'author' => 'Jonathan Heilmann',
	'author_email' => 'mail@jonathan-heilmann.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
            'ke_stats' => '1.2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);